"""changed Notes to Note in notes field in User model

Revision ID: b8e06000e760
Revises: decff3712f52
Create Date: 2022-11-24 12:43:20.233942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e06000e760'
down_revision = 'decff3712f52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
